[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

# slimのシンタックスハイライト
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

# ES6のシンタックスハイライト
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

