[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# gccでコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# .コマンドの強化
[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'unblevable/quick-scope'
hook_add = '''
highlight QuickScopePrimary guifg='#afff5f' gui=underline ctermfg=155 cterm=underline
highlight QuickScopeSecondary guifg='#5fffff' gui=underline ctermfg=81 cterm=underline
'''

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
hook_add = '''
map <C-j> <Plug>(edgemotion-j)
map <C-l> <Plug>(edgemotion-k)
'''

[[plugins]]
repo = 'phaazon/hop.nvim'
hook_add = '''
lua << EOF
  require'hop'.setup()
EOF
nmap s [hop]
xmap s [hop]
nnoremap <silent> [hop]w :HopWord<CR>
nnoremap <silent> [hop]l :HopLine<CR>
nnoremap <silent> [hop]f :HopChar1<CR>
'''

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add ='''
cnoreabb <silent><expr>s getcmdtype()==':' && getcmdline()=~'^s' ? 'OverCommandLine<CR><C-u>%s/<C-r>=get([], getchar(0), '')<CR>' : 's'
'''
